-- https://school.programmers.co.kr/learn/courses/30/lessons/131117
-- JOIN - GROUP BY - SUM 
SELECT A.PRODUCT_ID, PRODUCT_NAME, PRICE * SUM(AMOUNT) AS TOTAL_SALES 
FROM FOOD_PRODUCT A 
JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID