-- https://school.programmers.co.kr/learn/courses/30/lessons/131533
-- SUM 조건 잘 보자.. 
SELECT PRODUCT_CODE, (PRICE * SUM(SALES_AMOUNT)) AS SALES FROM PRODUCT 
JOIN OFFLINE_SALE SALE ON PRODUCT.PRODUCT_ID = SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE 
ORDER BY SALES DESC, PRODUCT_CODE