-- https://school.programmers.co.kr/learn/courses/30/lessons/59412
-- 시간 추출 (H - 24시간, h - 12시간)
SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS
-- SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT -> 이렇게도 가능
WHERE DATE_FORMAT(DATETIME, '%H') BETWEEN 9 AND 19
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY HOUR