-- https://school.programmers.co.kr/learn/courses/30/lessons/131529
-- SUBSTRING(컬럼, 시작IDX, 시작IDX 기준 몇개나) (SQL은 IDX 1부터 시작함)
SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(*) AS PRODUCTS FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY ASC