-- https://school.programmers.co.kr/learn/courses/30/lessons/59043
-- WHERE 날짜 빠른 순서 비교 
SELECT INS.ANIMAL_ID, INS.NAME FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME