-- https://school.programmers.co.kr/learn/courses/30/lessons/144855
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES FROM BOOK
JOIN BOOK_SALES SALES ON BOOK.BOOK_ID = SALES.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY
ORDER BY CATEGORY