-- https://school.programmers.co.kr/learn/courses/30/lessons/133025
-- LEFT JOIN 사용하기
SELECT A.FLAVOR FROM FIRST_HALF A INNER JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based' ORDER BY TOTAL_ORDER   
